// "Sessiz Su" hikayesi için 35 sinematik görsel prompt'u
// Dosya adları sırayla 01.png, 02.png ... 35.png olarak kaydedilecek

export const prompts = [
  "Altın saat ışığında kuraklıktan kurumuş devasa bir baraj gölü, ufka kadar uzanan çatlamış çamur zemin, uzakta sudan yükselen eski bir taş çan kulesi. Sinematik, kasvetli, 35mm film grenli.",
  "Kalın çamura saplanmış küçük bir ahşap tekne, yanında dizlerine kadar çamura batmış yalnız bir gazeteci, terk edilmiş baraj gölünde süzülen sis. Ürkütücü, sinematik ışıklandırma.",
  "Durgun bir gölden yükselen hayalet bir köyün yarı su altında kalmış çatıları, üzerinde dramatik fırtına bulutları. Fotogerçekçi, tedirgin edici atmosfer.",
  "Paslı, yosun kaplı bir kilise kapısı yarı aralık duruyor, karanlığa sızan loş altın ışık. Korku filmi atmosferi, sinematik.",
  "Çökmekte olan bir kilisenin içi, çürümüş ahşap sıralar, tavanda örümcek ağları, karanlığı yaran kalın tozlu güneş huzmeleri. Kasvetli, sinematik.",
  "Rüzgârsız havada usulca sallanan eski paslı bir kilise çanı, arkasında alacakaranlık gökyüzü. Ürkütücü, sessiz bir tedirginlik, sinematik ışıklandırma.",
  "Antik bir taş duvarda tuhaf, taze görünen su lekelerinin aşırı yakın çekimi. Ürkütücü doku, kasvetli ışıklandırma.",
  "Bir kamera vizöründen görünen sararmış eski nüfus kayıt defteri sayfası, sepya tonları. Bulunmuş görüntü (found-footage) tarzı korku.",
  "Titreyen ellerle tutulan bir kameranın yakın çekimi, ekranda hafifçe parlayan tek bir isim. Gergin, dramatik ışıklandırma.",
  "Karanlık bir kilise köşesinde tek başına oturan gazeteci, yüzünde şok ve korku. Sinematik chiaroscuro ışıklandırma.",
  "Kurdeleli küçük kırmızı bir çocuk ayakkabısı, ıslak çamura yarı gömülü, hafifçe parıldıyor. Ürkütücü, gerçekçi fotoğrafçılık.",
  "Küçük bir ayakkabıyı kalın çamurdan çıkarmak için uzanan bir el, arka planda bulanık hayalet köy silüeti.",
  "Yetişkin bir elde tutulan damlayan ıslak kırmızı çocuk ayakkabısının aşırı yakın çekimi. Sığ alan derinliği, sinematik.",
  "Tamamen karanlıkta tek ışık kaynağı olan parlayan bir telefon ekranı, hiçbir şebeke çubuğu görünmüyor. Gergin, sessiz korku atmosferi.",
  "Bilinmeyen bir numaradan gelen mesajın parlayan telefon ekranı, gölgeli bir el tarafından tutuluyor. Korku filmi ışıklandırması.",
  "Alacakaranlıkta terk edilmiş bir köy sokağında yürüyen yalnız bir figür, hemen arkasında sürüklenen ikinci bir gölge. Tedirgin edici geniş çekim.",
  "Çamurda iki set ayak izi — biri yetişkin, hemen yanında beliren çıplak küçük bir çocuk ayak izi. Ürkütücü kuşbakışı görünüm.",
  "Boş bir köy meydanında arkasına dönen bir adam, etrafta kimse yok, yüzünde korku. Sinematik korku çerçevelemesi.",
  "Karanlık, terk edilmiş bir evin penceresinden sızan titrek mum ışığı, dışarıdan izleyen bir silüet.",
  "Tozlu bir masa üzerinde eski deri ciltli bir günlük, sayfaları loş mum ışığında kendi kendine çevriliyor. Korku atmosferi.",
  "El yazısıyla dolu günlük sayfalarının aşırı yakın çekimi, mürekkep hâlâ ıslak ve parlak. Tedirgin edici detay çekimi.",
  "Gölgeler içinde gıcırdayan ahşap merdivenler, yukarıdan sarkan tek bir çıplak ampul. Kasvetli korku ışıklandırması.",
  "Karanlık bir duvarın tozunda görünmez bir parmakla çiziliyormuş gibi yavaşça beliren harfler. Ürkütücü yakın çekim.",
  "Sonsuza uzanan karanlık bir koridor, en uçta parıldayan tek bir ışık noktası. Tedirgin edici perspektif.",
  "Güvertesinde eski çıtırtılı bir radyo bulunan terk edilmiş bir balıkçı teknesi, arkasında sisli göl. Sinematik, sessiz bir kasvet.",
  "Eski bir radyodan yayılan görünmez ses dalgalarını çağrıştıran kasvetli bir gece sahnesi, soğuk mavi ay ışığı. Atmosferik.",
  "Rüzgârsız havada kendi kendine dalgalanan karanlık göl suyu, yüzeyde yansıyan ay ışığı. Tedirgin edici sinematik çekim.",
  "Güneşli bir günde nehirde yüzen iki çocuğun sepya tonlarında nostaljik anısı. Sıcak, rüya gibi ışıklandırma.",
  "Suya doğru uzanan bir elin dramatik ağır çekim yakın planı, parmak uçları başka bir ele değmek üzere.",
  "Su altından yüzeye doğru bakan bir açı, suyun içinden kırılan ışık. Ürkütücü ama bir o kadar güzel.",
  "Kurumuş bir gölün ortasında boğazına kadar çamura batmış debelenen bir figür, çaresiz ve dehşet verici. Sinematik geniş çekim.",
  "Sudan yükselen soluk küçük bir elin bir bileği kavrayışı. Karanlık, gergin korku ışıklandırması.",
  "Bütün bir köyün eriyip yeniden suya karıştığı sürrealist bir sahne. Rüya gibi geçiş, sinematik.",
  "Ay ışığında parıldayan sakin bir gece gölü, uzakta yüzen küçük kırmızı bir nokta. Sessiz, tedirgin edici atmosfer.",
  "Otel penceresinden karanlık göle bakan yorgun bir gazeteci silüeti, masada hafifçe parlayan bir telefon. Sinematik noir ışıklandırma."
];
